CREATE TABLE IF NOT EXISTS monitoring_assets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES companies(id), project_id UUID REFERENCES projects(id), assigned_user_id UUID REFERENCES users(id), asset_type TEXT NOT NULL, name TEXT NOT NULL, hostname TEXT, os_name TEXT, os_version TEXT, ip_address TEXT, mac_address TEXT, environment TEXT, location TEXT, serial_number TEXT, vendor TEXT, model TEXT, ownership TEXT, status TEXT NOT NULL DEFAULT 'active', last_seen_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS monitoring_agent_tokens (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_id UUID NOT NULL REFERENCES monitoring_assets(id) ON DELETE CASCADE, token_hash TEXT NOT NULL, name TEXT, revoked_at TIMESTAMPTZ, last_used_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS monitoring_checks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_id UUID NOT NULL REFERENCES monitoring_assets(id) ON DELETE CASCADE, check_type TEXT NOT NULL, name TEXT NOT NULL, target TEXT, config JSONB NOT NULL DEFAULT '{}', interval_seconds INT NOT NULL DEFAULT 60, timeout_seconds INT NOT NULL DEFAULT 10, enabled BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS monitoring_check_results (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), check_id UUID NOT NULL REFERENCES monitoring_checks(id) ON DELETE CASCADE, asset_id UUID NOT NULL REFERENCES monitoring_assets(id) ON DELETE CASCADE, status TEXT NOT NULL, observed_value NUMERIC, response_time_ms INT, message TEXT, raw_data JSONB NOT NULL DEFAULT '{}', checked_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS monitoring_metric_samples (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_id UUID NOT NULL REFERENCES monitoring_assets(id) ON DELETE CASCADE, cpu_percent NUMERIC, memory_percent NUMERIC, disk_percent NUMERIC, uptime_seconds BIGINT, process_count INT, raw_data JSONB NOT NULL DEFAULT '{}', collected_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS monitoring_alert_rules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_id UUID REFERENCES monitoring_assets(id) ON DELETE CASCADE, check_id UUID REFERENCES monitoring_checks(id) ON DELETE CASCADE, name TEXT NOT NULL, severity TEXT NOT NULL, condition_type TEXT NOT NULL, threshold_value NUMERIC, duration_seconds INT, auto_create_ticket BOOLEAN NOT NULL DEFAULT false, enabled BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS monitoring_alerts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES companies(id), project_id UUID REFERENCES projects(id), asset_id UUID NOT NULL REFERENCES monitoring_assets(id) ON DELETE CASCADE, check_id UUID REFERENCES monitoring_checks(id), rule_id UUID REFERENCES monitoring_alert_rules(id), ticket_id UUID REFERENCES tickets(id), severity TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', title TEXT NOT NULL, message TEXT, first_triggered_at TIMESTAMPTZ NOT NULL DEFAULT now(), last_triggered_at TIMESTAMPTZ NOT NULL DEFAULT now(), resolved_at TIMESTAMPTZ, assigned_user_id UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS uniq_open_monitoring_alert ON monitoring_alerts(asset_id, check_id, rule_id) WHERE status IN ('open','acknowledged');
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tickets_monitoring_alert_fk') THEN ALTER TABLE tickets ADD CONSTRAINT tickets_monitoring_alert_fk FOREIGN KEY (monitoring_alert_id) REFERENCES monitoring_alerts(id); END IF; END $$;
