import {Router} from 'express'; import crypto from 'crypto'; import bcrypt from 'bcryptjs'; import {crudRouter} from '../crud.js'; import {authenticate} from '../../middleware/auth.js'; import {requirePermission} from '../../middleware/requireRole.js'; import {asyncHandler,ApiError} from '../../middleware/errorHandler.js'; import {agentRateLimit} from '../../middleware/rateLimit.js'; import {q} from '../../db/pool.js'; import {evaluateMetricSample,createTicketForAlert} from '../../workers/alertEvaluator.js';
export const monitoringRouter=Router(); monitoringRouter.use('/monitoring/assets',crudRouter('monitoring_assets','monitoring')); monitoringRouter.use('/monitoring/alerts',crudRouter('monitoring_alerts','monitoring')); monitoringRouter.use('/monitoring/email-ingestions',crudRouter('email_ingestions','monitoring')); monitoringRouter.use('/monitoring/documents',crudRouter('documents','monitoring')); monitoringRouter.use('/monitoring/mobile-devices',crudRouter('mobile_devices','monitoring')); monitoringRouter.use('/monitoring/remote-control-sessions',crudRouter('remote_control_sessions','monitoring')); monitoringRouter.use('/monitoring/patch-jobs',crudRouter('patch_jobs','monitoring')); monitoringRouter.use('/monitoring/siem-correlations',crudRouter('siem_correlations','monitoring'));
monitoringRouter.post('/monitoring/assets/:id/tokens',authenticate,requirePermission('monitoring',true),asyncHandler(async(req,res)=>{const raw=crypto.randomBytes(32).toString('hex'); const hash=await bcrypt.hash(raw,12); const {rows}=await q('insert into monitoring_agent_tokens(asset_id,token_hash,name) values($1,$2,$3) returning id,asset_id,name,created_at',[req.params.id,hash,req.body.name]); res.status(201).json({...rows[0],token:raw})}));
monitoringRouter.get('/monitoring/assets/:id/checks',authenticate,requirePermission('monitoring'),asyncHandler(async(req,res)=>res.json({data:(await q('select * from monitoring_checks where asset_id=$1',[req.params.id])).rows})));
monitoringRouter.post('/monitoring/assets/:id/checks',authenticate,requirePermission('monitoring',true),asyncHandler(async(req,res)=>{const b=req.body; const {rows}=await q('insert into monitoring_checks(asset_id,check_type,name,target,config,interval_seconds,timeout_seconds,enabled) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[req.params.id,b.check_type,b.name,b.target,b.config||{},b.interval_seconds||60,b.timeout_seconds||10,b.enabled!==false]); res.status(201).json(rows[0])}));
monitoringRouter.get('/monitoring/assets/:id/results',authenticate,requirePermission('monitoring'),asyncHandler(async(req,res)=>res.json({data:(await q('select * from monitoring_check_results where asset_id=$1 order by checked_at desc limit 500',[req.params.id])).rows})));
monitoringRouter.get('/monitoring/assets/:id/metrics',authenticate,requirePermission('monitoring'),asyncHandler(async(req,res)=>res.json({data:(await q('select * from monitoring_metric_samples where asset_id=$1 order by collected_at desc limit 500',[req.params.id])).rows})));
monitoringRouter.post('/monitoring/alerts/:id/acknowledge',authenticate,requirePermission('monitoring',true),asyncHandler(async(req,res)=>res.json((await q("update monitoring_alerts set status='acknowledged',assigned_user_id=$2,updated_at=now() where id=$1 returning *",[req.params.id,req.user!.id])).rows[0])));
monitoringRouter.post('/monitoring/alerts/:id/resolve',authenticate,requirePermission('monitoring',true),asyncHandler(async(req,res)=>res.json((await q("update monitoring_alerts set status='resolved',resolved_at=now(),updated_at=now() where id=$1 returning *",[req.params.id])).rows[0])));
monitoringRouter.post('/monitoring/alerts/:id/create-ticket',authenticate,requirePermission('helpdesk',true),asyncHandler(async(req,res)=>res.status(201).json(await createTicketForAlert(String(req.params.id),req.user!.id))));
async function agentAuth(req:any){const assetId=req.body.assetId||req.params.id; const token=(req.headers.authorization||'').replace(/^Bearer /,'')||req.body.token; const toks=(await q('select * from monitoring_agent_tokens where asset_id=$1 and revoked_at is null',[assetId])).rows; for(const t of toks){if(await bcrypt.compare(token,t.token_hash)){await q('update monitoring_agent_tokens set last_used_at=now() where id=$1',[t.id]); return assetId}} throw new ApiError(401,'INVALID_AGENT_TOKEN','Invalid agent token')}
monitoringRouter.post('/agent/heartbeat',agentRateLimit,asyncHandler(async(req,res)=>{const id=await agentAuth(req); await q('update monitoring_assets set last_seen_at=now(),hostname=coalesce($2,hostname),updated_at=now() where id=$1',[id,req.body.hostname]); res.json({ok:true})}));
monitoringRouter.post('/agent/metrics',agentRateLimit,asyncHandler(async(req,res)=>{const id=await agentAuth(req), m=req.body.metrics||{}; await q('update monitoring_assets set last_seen_at=now(),hostname=coalesce($2,hostname),os_name=coalesce($3,os_name),os_version=coalesce($4,os_version),ip_address=coalesce($5,ip_address),mac_address=coalesce($6,mac_address),updated_at=now() where id=$1',[id,req.body.hostname,req.body.os?.name,req.body.os?.version,req.body.network?.ipAddresses?.[0],req.body.network?.macAddresses?.[0]]); const s=(await q('insert into monitoring_metric_samples(asset_id,cpu_percent,memory_percent,disk_percent,uptime_seconds,process_count,raw_data,collected_at) values($1,$2,$3,$4,$5,$6,$7,coalesce($8,now())) returning *',[id,m.cpuPercent,m.memoryPercent,m.diskPercent,m.uptimeSeconds,m.processCount,req.body,req.body.collectedAt])).rows[0]; await evaluateMetricSample(s); res.status(201).json({ok:true})}));
monitoringRouter.post('/monitoring/siem-correlations/:id/resolve',authenticate,requirePermission('monitoring',true),asyncHandler(async(req,res)=>res.json((await q("update siem_correlations set status='resolved',updated_at=now() where id=$1 returning *",[req.params.id])).rows[0])));
monitoringRouter.post('/agent/register',agentRateLimit,asyncHandler(async(req,res)=>res.json({ok:true,message:'Create asset/token in portal, then configure agent.'}))); monitoringRouter.post('/agent/processes',agentRateLimit,asyncHandler(async(req,res)=>{await agentAuth(req); res.json({ok:true})})); monitoringRouter.post('/agent/services',agentRateLimit,asyncHandler(async(req,res)=>{await agentAuth(req); res.json({ok:true})}));
